name: check
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  eval:
    name: eval ${{ matrix.host }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host:
          - atlas
          - proton
          - lenix
          - webster
          - thinkpad
          - bread
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            access-tokens = github.com=${{ secrets.FLAKE_PRIVATE_TOKEN }}
      - name: Evaluate ${{ matrix.host }}
        run: |
          nix eval --raw \
            .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel.drvPath
  formatting:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            access-tokens = github.com=${{ secrets.FLAKE_PRIVATE_TOKEN }}
      - name: Check treefmt formatting
        run: nix build --no-link .#checks.x86_64-linux.formatting
